backend:
  name: git-gateway
  branch: feature/create-pages-for-content

publish_mode: editorial_workflow

media_folder: static/images
public_folder: /images

collections:
  - label: "Site Options"
    name: "options"
    editor:
      preview: false
    files:
      - label: "Metadata"
        name: "metadata"
        file: "src/assets/metadata.json"
        fields:
          - label: "General"
            name: "general"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Language", name: "language", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Keywords", name: "keywords", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
          - label: "Social"
            name: "social"
            widget: "object"
            fields:
              - {label: "Avatar", name: "avatar", widget: "string"}
              - {label: "Avatar Small", name: "avatarSmall", widget: "string"}
              - {label: "Banner", name: "banner", widget: "string"}
              - {label: "Banner Width", name: "bannerWidth", widget: "number"}
              - {label: "Banner Height", name: "bannerHeight", widget: "number"}
              - {label: "Facebook", name: "facebook", widget: "string"}
              - {label: "LinkedIn", name: "linkedin", widget: "string"}
          - label: "Contact"
            name: "contact"
            widget: "object"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Address", name: "address", widget: "string"}
              - {label: "Postal Code", name: "postalCode", widget: "string"}
              - {label: "Phone", name: "phone", widget: "string"}
              - {label: "Email", name: "email", widget: "string"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - label: "Intro"
            name: "intro"
            widget: "object"
            fields:
              - {label: "Image", name: "image", widget: "image"}
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "text"}
              - {label: "Author", name: "author", widget: "string"}
          - label: "Cards"
            name: "cards"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Description", name: "description", widget: "text", required: false}
              - {label: "Link", name: "link", widget: "string", required: false}
              - {label: "Image", name: "image", widget: "image", required: false}
              - {label: "Color", name: "color", widget: "select", options: ["primary", "secondary", "tertiary"], required: false}
              - {label: "Size", name: "size", widget: "select", options: ["1", "2", "3"]}
      - file: "src/pages/kracht-inzicht/index.md"
        label: "Kracht Inzicht Page"
        name: "kracht-inzicht"
        fields:
          - label: "Template Key"
            name: "templateKey"
            widget: "hidden"
            default: "content-page"
          - label: "Intro"
            name: "intro"
            widget: "object"
            fields:
              - {label: "Image", name: "image", widget: "image"}
          - label: "Content"
            name: "content"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Left", name: "left", buttons: ["bold","italic","heading-one","heading-two","bulleted-list","numbered-list"], widget: "markdown"}
              - {label: "Right", name: "right", buttons: ["bold","italic","heading-one","heading-two","bulleted-list","numbered-list"], widget: "markdown"}
          - label: "Cards"
            name: "cards"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Description", name: "description", widget: "text", required: false}
              - {label: "Image", name: "image", widget: "image", required: false}
              - {label: "Color", name: "color", widget: "select", options: ["primary", "secondary", "tertiary"], required: false}
              - {label: "Size", name: "size", widget: "select", options: ["1", "2", "3"]}
      - file: "src/pages/volwassenen/index.md"
        label: "Volwassenen Page"
        name: "volwassenen"
        fields:
          - label: "Template Key"
            name: "templateKey"
            widget: "hidden"
            default: "content-page"
          - label: "Intro"
            name: "intro"
            widget: "object"
            fields:
              - {label: "Image", name: "image", widget: "image"}
          - label: "Content"
            name: "content"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Left", name: "left", buttons: ["bold","italic","heading-one","heading-two","bulleted-list","numbered-list"], widget: "markdown"}
              - {label: "Right", name: "right", buttons: ["bold","italic","heading-one","heading-two","bulleted-list","numbered-list"], widget: "markdown"}
          - label: "Cards"
            name: "cards"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Description", name: "description", widget: "text", required: false}
              - {label: "Image", name: "image", widget: "image", required: false}
              - {label: "Color", name: "color", widget: "select", options: ["primary", "secondary", "tertiary"], required: false}
              - {label: "Size", name: "size", widget: "select", options: ["1", "2", "3"]}
      - file: "src/pages/kinderen/index.md"
        label: "Kinderen Page"
        name: "kinderen"
        fields:
          - label: "Template Key"
            name: "templateKey"
            widget: "hidden"
            default: "content-page"
          - label: "Intro"
            name: "intro"
            widget: "object"
            fields:
              - {label: "Image", name: "image", widget: "image"}
          - label: "Content"
            name: "content"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Left", name: "left", buttons: ["bold","italic","heading-one","heading-two","bulleted-list","numbered-list"], widget: "markdown"}
              - {label: "Right", name: "right", buttons: ["bold","italic","heading-one","heading-two","bulleted-list","numbered-list"], widget: "markdown"}
          - label: "Cards"
            name: "cards"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Description", name: "description", widget: "text", required: false}
              - {label: "Image", name: "image", widget: "image", required: false}
              - {label: "Color", name: "color", widget: "select", options: ["primary", "secondary", "tertiary"], required: false}
              - {label: "Size", name: "size", widget: "select", options: ["1", "2", "3"]}
      - file: "src/pages/opstellingen/index.md"
        label: "Opstellingen Page"
        name: "opstellingen"
        fields:
          - label: "Template Key"
            name: "templateKey"
            widget: "hidden"
            default: "content-page"
          - label: "Intro"
            name: "intro"
            widget: "object"
            fields:
              - {label: "Image", name: "image", widget: "image"}
          - label: "Content"
            name: "content"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Left", name: "left", buttons: ["bold","italic","heading-one","heading-two","bulleted-list","numbered-list"], widget: "markdown"}
              - {label: "Right", name: "right", buttons: ["bold","italic","heading-one","heading-two","bulleted-list","numbered-list"], widget: "markdown"}
          - label: "Cards"
            name: "cards"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Description", name: "description", widget: "text", required: false}
              - {label: "Image", name: "image", widget: "image", required: false}
              - {label: "Color", name: "color", widget: "select", options: ["primary", "secondary", "tertiary"], required: false}
              - {label: "Size", name: "size", widget: "select", options: ["1", "2", "3"]}
      - file: "src/pages/hooggevoeligheid/index.md"
        label: "Hooggevoeligheid Page"
        name: "hooggevoeligheid"
        fields:
          - label: "Template Key"
            name: "templateKey"
            widget: "hidden"
            default: "content-page"
          - label: "Intro"
            name: "intro"
            widget: "object"
            fields:
              - {label: "Image", name: "image", widget: "image"}
          - label: "Content"
            name: "content"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Left", name: "left", buttons: ["bold","italic","heading-one","heading-two","bulleted-list","numbered-list"], widget: "markdown"}
              - {label: "Right", name: "right", buttons: ["bold","italic","heading-one","heading-two","bulleted-list","numbered-list"], widget: "markdown"}
          - label: "Cards"
            name: "cards"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Description", name: "description", widget: "text", required: false}
              - {label: "Image", name: "image", widget: "image", required: false}
              - {label: "Color", name: "color", widget: "select", options: ["primary", "secondary", "tertiary"], required: false}
              - {label: "Size", name: "size", widget: "select", options: ["1", "2", "3"]}